export const CORREO_EXISTE = 'CORREO_EXISTE';
export const LOGIN_START_SUCCESS = 'LOGIN_START_SUCCESS';

export const SEARCH_USERALL_SUCCESS = 'SEARCH_USERALL_SUCCESS';
export const SEARCH_USERALL_ERROR = 'SEARCH_USERALL_ERROR';
export const SEARCH_USER_FILTER = 'SEARCH_USER_FILTER';

export const SEARCH_PRODUCTSALL_SUCCESS = 'SEARCH_PRODUCTSALL_SUCCESS';
export const SEARCH_PRODUCTSALL_ERROR = 'SEARCH_PRODUCTSALL_ERROR';
export const SEARCH_PRODUCTS_FILTER = 'SEARCH_PRODUCTS_FILTER';

export const SEARCH_ORDENESALL_SUCCESS = 'SEARCH_ORDENESALL_SUCCESS';
export const SEARCH_ORDENESALL_ERROR = 'SEARCH_ORDENESALL_ERROR';
export const SEARCH_ORDENES_FILTER = 'SEARCH_ORDENES_FILTER';